services:
  db:
    image: postgres:16.3
    restart: always
    container_name: todos-postgres-db
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db-data:
