basePath: /v1
definitions:
  main.healthCheckResponse:
    properties:
      env:
        type: string
      status:
        type: string
      version:
        type: string
    type: object
  main.jsonErrorResponseEnvelope:
    properties:
      error:
        type: string
    type: object
  main.jsonResponseEnvelope:
    properties:
      data: {}
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample api for todo list application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Todo List CRUD Application
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Returns the health status, environment, and version of the application.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/main.jsonResponseEnvelope'
            - properties:
                data:
                  $ref: '#/definitions/main.healthCheckResponse'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.jsonErrorResponseEnvelope'
      summary: Health Check
      tags:
      - Health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
